### PR TITLE
Refactor Lucene Audit Logger and implement SQL Audit Logger

### PR DESCRIPTION
**Pull request by markgibbons25**

### CODE REVIEW

**Comment by markgibbons25** [comment]
@JeffDarchuk mostly working, still a few bits and pieces left to do / cleanup

**Comment by markgibbons25** [comment]
Implements #71

**Comment by markgibbons25** [comment]
Still TODO: update readme, but will wait on feedback first.

**Comment by JeffDarchuk** [comment]
I'm on vacation currently without my computer.  I'll be able to check it out Monday.  Sounds promising though

**Comment by JeffDarchuk** [comment]
is this removing the lucene functionality entirely or just adding an option to use an SQL database for storage?  Also, is the database expected to be manually created?

**Comment by markgibbons25** [comment]
> is this removing the lucene functionality entirely or just adding an option to use an SQL database for storage? 
Just an option, it still defaults to lucene
> Also, is the database expected to be manually created?
Yes - dacpac is included although I am not sure how you want to include that in the nuget package.
Also - readme update is done.

**Comment by JeffDarchuk** [comment]
ah, sounds good, since it requires manual database creation, we could probably just store it in the repo and point people to it via the readme.md.  It's too bad we can't just store this information in an already existing Sitecore database somehow

**Comment by markgibbons25** [comment]
It can use an already existing database, but I'd never recommend people add tables to system databases for a few reasons:
* Upgradeability - makes it more difficult to upgrade
* Security - reducing the attack surface if there's any SQL injection vulnerability
* Monitoring - having a separate DB you can monitor for growth and resource usage

I'll update the config and readme as you suggest with a link to the dacpac.

**Comment by JeffDarchuk** [comment]
oh yeah, couldn't agree more.  I was thinking more along the lines of jam it in an existing table somewhere that would make sense, and definitely wishful thinking.

**Comment by markgibbons25** [comment]
I've been using this in a large prod environment for the last 10 days, thousands of events logged, performance is all good, no issues. Had some good feedback on how useful it is already.
One thing that would be nice is to track "system" events a bit better, they come through as anonymous, things like TDS / unicorn sync, scheduled jobs.

**Comment by JeffDarchuk** [comment]
great, that's good enough for me, nice work on this!  I'll cut a new release tomorrow morning

**Comment by JeffDarchuk** [comment]
alpha3 includes this change.  My plan for an official 1.6.0 release is to test it myself thoroughly with my current client, this will likely be about a month from now that i can get the testing done.

**Pull request merged**
